Repository MrTroble/Open-Signals, pull requests merged in 2021-04, with the labels that each got.

#55 [Untested] Fixed block pick part1 and signals being out of loaded chunks!
  changelog.md
  src/main/java/eu/gir/girsignals/GirsignalsMain.java
  src/main/java/eu/gir/girsignals/SEProperty.java
  src/main/java/eu/gir/girsignals/blocks/GhostBlock.java
  src/main/java/eu/gir/girsignals/blocks/Signal.java
  src/main/java/eu/gir/girsignals/blocks/TrackIOBlock.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalHL.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalHV.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalKS.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalLF.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalSHLight.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalTram.java
  src/main/java/eu/gir/girsignals/guis/GuiPlacementtool.java
  src/main/java/eu/gir/girsignals/guis/GuiSignalController.java
  src/main/java/eu/gir/girsignals/init/GIRBlocks.java
  src/main/java/eu/gir/girsignals/init/GIRModels.java
  src/main/java/eu/gir/girsignals/init/GIRNetworkHandler.java
  src/main/java/eu/gir/girsignals/items/Linkingtool.java
  src/main/java/eu/gir/girsignals/items/Placementtool.java
  src/main/java/eu/gir/girsignals/models/GIRCustomModelLoader.java
  src/main/java/eu/gir/girsignals/models/SignalCustomModel.java
  src/main/java/eu/gir/girsignals/proxy/CommonProxy.java
  src/main/java/eu/gir/girsignals/tileentitys/SignalControllerTileEntity.java
  src/main/java/eu/gir/girsignals/tileentitys/SignalSpecialRenderer.java
  src/main/java/eu/gir/girsignals/tileentitys/SignalTileEnity.java
  src/main/java/eu/gir/girsignals/tileentitys/TrackIOTileEntity.java
  src/main/resources/assets/girsignals/blockstates/trackio.json
  src/main/resources/assets/girsignals/models/block/trackio.json
  src/main/resources/assets/girsignals/models/item/trackio.json
  src/main/resources/assets/girsignals/textures/blocks/trackio.png
Labels: Don't delete after merge, bug, untested

#56 Added signal naming for SH signals and fixed some backend stuff
  changelog.md
  src/main/java/eu/gir/girsignals/blocks/Signal.java
  src/main/java/eu/gir/girsignals/blocks/TrackIOBlock.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalHL.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalHV.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalKS.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalLF.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalSHLight.java
  src/main/java/eu/gir/girsignals/blocks/signals/SignalTram.java
  src/main/java/eu/gir/girsignals/guis/GuiPlacementtool.java
  src/main/java/eu/gir/girsignals/init/GIRItems.java
  src/main/java/eu/gir/girsignals/items/Placementtool.java
  src/main/java/eu/gir/girsignals/tileentitys/SignalSpecialRenderer.java
  src/main/java/eu/gir/girsignals/tileentitys/SignalTileEnity.java
Labels: Don't delete after merge, tested

#60 NE Signs were added to GIRSignals
  changelog.md
  src/main/java/eu/gir/girsignals/EnumSignals.java
  src/main/java/eu/gir/girsignals/blocks/SignalNE.java
  src/main/java/eu/gir/girsignals/init/GIRBlocks.java
  src/main/java/eu/gir/girsignals/models/GIRCustomModelLoader.java
  src/main/resources/assets/girsignals/lang/de_de.lang
  src/main/resources/assets/girsignals/lang/en_us.lang
  src/main/resources/assets/girsignals/models/block/el/el_arrow.json
  src/main/resources/assets/girsignals/models/block/lf/lf3_5_7.json
  src/main/resources/assets/girsignals/textures/blocks/ne3_4.png
  src/main/resources/assets/girsignals/textures/blocks/ne3_5.png
Labels: tested

#61 Models and textures cleanup
  changelog.md
  src/main/java/eu/gir/girsignals/models/GIRCustomModelLoader.java
  src/main/resources/assets/girsignals/models/block/ne/ne2.json
  src/main/resources/assets/girsignals/models/block/ne/ne2_2.json
  src/main/resources/assets/girsignals/models/block/ne/ne2_3.json
  src/main/resources/assets/girsignals/models/block/ne/ne3_4.json
  src/main/resources/assets/girsignals/models/block/ne/ne6.json
  src/main/resources/assets/girsignals/models/block/ne/ne6_mast.json
  src/main/resources/assets/girsignals/textures/blocks/ne3_4.png
  src/main/resources/assets/girsignals/textures/blocks/ne3_5.png
Labels: Don't delete after merge, tested
